name: 'rsync-by-joe'
description: 'Synchronize files to a remote server with rsync.'
inputs:
  host: # Remote host address
    description: 'Remote host to connect to'
    required: true
  port: # Optional remote hos address
    description: '(Optional) remote host port (defaults to 22)'
    default: 22
  username: # User to connect to
    description: 'Username on the remote host.'
    required: true
  ssh_key: # Private SSH key to authenticate with.
    description: 'Private SSH key to connect with. Make sure the matching public key is in the remote authorized_keys file.'
    required: true
  ssh_passkey: # Passkey to decrypt the private key.
    description: 'Passkey for the private SSH key.'
    required: false
  ssh_host_fingerprint: # SSH of the host. Optional, but highly recommended.
    description: '(Optional) Fingerprint of the remote host. It is *highly* recommended that you set this, instead of automatically trusting the remote key.'
    required: false

  # Optional paths to command-line tools.
  rsync_path: # Optional path to the rsync binary.
    description: '(Optional) Full path to rsync if not in the PATH.'
    required: false
  ssh_bin_path:
    description: '(Optional) Full path to - or name of - the SSH client if not in the PATH.'
    required: false
  ssh_keyscan_path:
    description: '(Optional) Full path to - or name of - ssh-keyscan if not in the PATH.'
    required: false
  ssh_keygen_path:
    description: '(Optional) Full path to - or name of - ssh-keygen if not in the PATH.'
    required: false

  rsync_args: # Optional arguments to use in lieu of the defaults.
    description: '(Optional) Override the default rsync arguments ["-avzr", "--delete"] with your own.'
    required: false
    default: |
      -avzr
      --delete
      --mkpath
  source: # Path of the files to copy.
    description: 'Source path of files to copy.'
    required: true
  exclude: # Single exclude pattern.
    description: 'Exclusion pattern.'
    required: false
    default: 'node_modules/' # Defaults to the node_modules directory.
  dest: # Destination path of the copy.
    description: 'Destination path of the files on the remote host.'
    required: true
  path_extras: # Extra segments to append to PATH.
    description: '(Optional) An array of additional segments to add to PATH. Use this if the necessary executables are installed in non-standard locations.'
    required: false

outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
