name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USER }}
        ssh_key: ${{ secrets.TEST_SSH_KEY }}
        source: '/'
        dest: '/home/${{ secrets.TEST_USER }}/tmp/tmptmptmp'

  # test action works running from the graph
  # TODO: this test is from the boilerplate projec.
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: ./
  #     with:
  #       milliseconds: 1000
