name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - next
      - 'releases/*'

jobs:
  # unit tests on Github-hosted runner.
  units:
    runs-on: ubuntu-latest
    needs: self_hosted_units
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # integration test using secrets on Githut-hosted runner.
  test:
    runs-on: ubuntu-latest
    needs: self_hosted_test
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USER }}
        ssh_key: ${{ secrets.TEST_SSH_KEY }}
        source: '/'
        dest: '/home/${{ secrets.TEST_USER }}/tmp/tmptmptmp'

  # self-hosted unit tests
  self_hosted_units:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # self-hosted integration test.
  self_hosted_test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USER }}
        ssh_key: ${{ secrets.TEST_SSH_KEY }}
        source: '/'
        dest: '/home/${{ secrets.TEST_USER }}/tmp/tmptmptmp'
